language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - npm install -g serverless
script:
  - python -m pytest test_class.py
deploy:
  provider: script
  script: serverless deploy --stage staging
  on:
    branch: master