language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - npm install -g serverless
before_script:
  sudo rm /etc/boto*
script:
  - python -m pytest -v
deploy:
  provider: script
  script: serverless deploy --stage staging
  on:
    branch: master